### ISSUE TITLE
Error stopping music player from working

### ISSUE THREAD

**Issue by donosean** [Twentysix26/Red-DiscordBot#10]
Checking for permission to "manage_messages" on line 1378 of red.py prevents the Youtube player from working as it hangs while checking for permissions to manage messages:
```python
return message.channel.permissions_for(message.server.me).manage_messages
```
 Changing the line as such should fix the issue:
```python
return message.channel.permissions_for(message.server.me).can_manage_messages
```

**Comment by Twentysix26** [comment]
You're using an outdated version of discord.py, [the syntax was changed](http://rapptz.github.io/discord.py/async/api.html#discord.Permissions.manage_messages).
Please install the version we're using:
`pip install git+git://github.com/Rapptz/discord.py.git@5a1d7a2d942c75a2f374b4b0add6ad50fdd227d7`
