### ISSUE TITLE
twitch.json channel entries are disappearing

### ISSUE THREAD

**Issue by Dspradau** [Twentysix26/Red-DiscordBot#11]
For some reason the twitch.json file will clear itself of any entries once in a while. Only one Twitch channel was added.

I did change the CHECK_DELAY to 60 because I was running into an issue where the streamer or Twitch was having broadcast issues and with a delay of 10 would pick up on the restart of the stream causing a repeat of the live message. I don't believe that is what is causing my issue though.

The only thing I can think of that is causing this is the section of twitchAlert that involves finding an error in the Twitch API causing the stream to be removed from the list.

**Comment by Twentysix26** [comment]
Are you sure you're on the latest commit? Back when I released the twitch alert system update I've made a mistake and a generic error was enough for the stream check to be deleted. I released the fix [4 hours later](https://github.com/Twentysix26/Red-DiscordBot/commit/be4ccc4bfc4c760608ced79d9f36ef2d59c23489)

**Comment by Dspradau** [comment]
Good call. Did not have that commit. Thank you! Closed.
