### ISSUE TITLE
Suggestion: Soundcloud functionality

### ISSUE THREAD

**Issue by FFZendikar** [Twentysix26/Red-DiscordBot#13]
As stated in the title; not sure on the difficulty of implementing it.

**Comment by KawaiiPotato** [comment]
Soundcloud does have an API so I presume the functionality is actionable.

Read: https://developers.soundcloud.com/docs/api/guide#playing

There is also the route of extracting the streaming URI then downloading the source... I am not 100% on how actionable this is.

**Comment by crysis909** [comment]
I have already the code but i am very new in python, so i don't know how i can stream the mp3.

**Comment by dong-brian** [comment]
Similarly, my friends would like spotify support.

**Comment by aqqadk** [comment]
Same +1

**Comment by Twentysix26** [comment]
Soundcloud is now supported (v2)
