### ISSUE TITLE
Repeat playlist

### ISSUE THREAD

**Issue by DrVagax** [Twentysix26/Red-DiscordBot#15]
Feature request, but i like it if i could make it play some random songs while no one suggests a youtube video, having the bit silent is sometimes a bit awkward.

So in other words, !repeatplaylist [playlist] would be cool to have it replay it a infinite time or perhaps a mode so it plays a random song from the cache once no one requested anything.

**Comment by Twentysix26** [comment]
In case you haven't noticed, playlists already loop by default. The only thing that don't are videos requested with !youtube

**Comment by DrVagax** [comment]
Woops, i have yet to go through the entire playlist and didn't noticed this was in already, could be considered closed then.
