### ISSUE TITLE
Limit usage of creating/deleting custom commands by role

### ISSUE THREAD

**Issue by dong-brian** [Twentysix26/Red-DiscordBot#17]
Custom commands are fun to play with, but I think it would be better if there was an option to limit the usage of the !addcom and !delcom commands to admins or another role.

**Comment by Twentysix26** [comment]
It's undocumented (need to finish the wiki) but it's already a thing.
In settings.json change the value of `EDIT_CC_ADMIN_ONLY` from false to true. This will restrict the use of the 3 commands to the admin role.
There's a similar setting for trivia too.

**Comment by dong-brian** [comment]
Okay cool!  When I get the chance I plan on forking this and making my own changes tailored to the server I run (if you don't mind).  Thanks for making this.

**Comment by Twentysix26** [comment]
You're free to modify it as you wish, as the license states. Have fun =)
