### ISSUE TITLE
Music player error

### ISSUE THREAD

**Issue by geddoe** [Twentysix26/Red-DiscordBot#2]
Hi, I'm getting this error sometimes, and when it happens it'll skip the song it is currently playing.

[tls @ 00000228e2ef6d40] Error in the pull function.
[aac @ 00000228e2f8a740] Input buffer exhausted before END element found
Error while decoding stream #0:0: Invalid data found when processing input
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000228e2f0ae80] stream 0, offset 0x5740ea: partial file
"google video link" Invalid data found when processing input

another one: 

[tls @ 000001619ee46f60] Error in the pull function.
[aac @ 000001619f455700] Input buffer exhausted before END element found
Error while decoding stream #0:0: Invalid data found when processing input
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001619ee5ae80] stream 0, offset 0x388076: partial file
"google video link" Invalid data found when processing input

**Comment by Twentysix26** [comment]
I get this problem as well sometimes. I'll try to look into it.

**Comment by Twentysix26** [comment]
Seems like an issue with youtube_dl, a lot of people are getting it. The new download mode is default now and it works much better than streaming videos.

**Comment by geddoe** [comment]
I haven't had this problem since switching to the download mode.
