### ISSUE TITLE
TwitchAlert task crashing bot

### ISSUE THREAD

**Issue by StarBruck** [Twentysix26/Red-DiscordBot#25]
About every five minutes I get this: 
[17/01/2016 17:52] ERROR: type object got multiple values for keyword argument '
mute'
Task was destroyed but it is pending!
task: <Task pending coro=<twitchAlert() running at red.py:1646> wait_for=<Future
 pending cb=[Task._wakeup()]>>
Why does it keep doing this? The Twitch.json is empty and nobody has used a twitch command in my server.

**Comment by Twentysix26** [comment]
https://github.com/Twentysix26/Red-DiscordBot/wiki/Troubleshooting
