### ISSUE TITLE
!image fix and !twitchemotes command

### ISSUE THREAD

**Issue by AdamCrowley1988** [Twentysix26/Red-DiscordBot#29]
Pls man fix image and add !twitchemotes "usernametwitch", so you can watch all the emoticon of that username twitch

**Comment by Rippner** [comment]
+1

**Comment by AdamCrowley1988** [comment]
thanks man I hope the developer listen my request because i need those commands

**Comment by Rippner** [comment]
he's just a pusillanime

**Comment by crysis909** [comment]
@AdamCrowley1988, at the moment he can't fix the !image command because the api is dead / no longer available.
