### ISSUE TITLE
Soundcloud [Question]

### ISSUE THREAD

**Issue by crysis909** [Twentysix26/Red-DiscordBot#32]
I wrote a little feature to play single songs from soundcloud but the api doesn't use async / aiohttp. My question is should i make a pull requests or not. The code isn't really finished too only to test the new function.

**Comment by Twentysix26** [comment]
If it's blocking, no. Also, youtube_dl, which the bot is using, can stream/download songs from a multitude of websites, soundcloud included. Just haven't had the chance to implement it yet

**Comment by aqqadk** [comment]
any eta? <3 :)

**Comment by WingsOfAltair** [comment]
You need to be patient, my friend.

**Comment by Twentysix26** [comment]
Soundcloud is now supported (v2)
