### ISSUE TITLE
Wrong settings in settings.json

### ISSUE THREAD

**Issue by artursskutans** [Twentysix26/Red-DiscordBot#33]
After recent update redbot doesn't start. Commander says:

![redbot_issue](https://cloud.githubusercontent.com/assets/11672200/12578937/9d93e52a-c42c-11e5-9a3e-a394d3ab949e.png)

But all my credentials are right. How can I fix this problem?

**Comment by crysis909** [comment]
This error normally shows up if your email / password in the json/settings.json file is wrong.

**Comment by artursskutans** [comment]
But my information is correct, I checked that many times

**Comment by Twentysix26** [comment]
http://rapptz.github.io/discord.py/async/api.html?discord.LoginFailure#discord.LoginFailure

*Exception that’s thrown when the Client.login() function fails to log you in from improper credentials or some other misc. failure.*

Can't say I've ever experienced this error when the credentials are right. 99% of the time that's the problem.
Try deleting your settings.json and start it again.

**Comment by artursskutans** [comment]
Also did that many times. Didn't help.

**Comment by crysis909** [comment]
The last thing you can try is to use another valid email and password in the settings.json

**Comment by artursskutans** [comment]
I created a new account. Put valid credentials in settings.json but problem was the same. Didn't help.

**Comment by Mikegrann** [comment]
Looking at discord.py, it seems like the exception is thrown as a result of an HTTP 400 error response, regardless of the cause. A couple of options:
* Reinstall/Update discord.py - perhaps an older implementation of the Discord API used different headers and attempting to connect through the older API simply won't work. This is only likely a problem if your version of discord.py is quite old, and even then I'm not sure their login API has gone through any major changes. 
* Try to contact the writer of discord.py. He might have a better clue about the actual API and possible reasons for that error code. 
* Check your http logs and figure out the reason for the error code. 400 is a bit of a catch all that pretty much means "you're trying to connect to me the wrong way" but you might be able to see the specific reason the connection was refused here. 
* Start packet sniffing, I guess? You can take a look at your request packets and check the data in them. You might see something that went wrong -  eg an issue with a username that has strange symbols that aren't escaped or something along these lines. Probably not really worth it.
