### ISSUE TITLE
problem when playing localtracks

### ISSUE THREAD

**Issue by LeaderPeace** [Twentysix26/Red-DiscordBot#38]
http://hizliresim.com/1Mo8Ob I need help.

**Comment by Asute** [comment]
Hi, I can't really understand what the error is on your console, but I did a bit of research to try to find it. 
If it translates to something like _ An established connection was aborted by the software
e in your host machine_, it is most likely a problem on your end. If your connection was randomly closed or unstable, the bot would have difficulty connecting through Discord.

**Comment by Asute** [comment]
I'm going to assume that you've solved the issue and will now close this.

If not, that error is on your end (your connection). Sometimes restarting the console/bot fixes it.
