### ISSUE TITLE
Small bug in getPreviousSong(self)

### ISSUE THREAD

**Issue by Atlowell** [Twentysix26/Red-DiscordBot#40]
The first line under the except should be
song = self.playlist[len(self.playlist)-1]
not
song = self.playlist[len(self.current)-1]

The idea is to wrap around the array if you are at the beginning.  The result is that the prev/previous command doesn't work correctly.

P.S. I have copied the repo for use on a private server, and have edited the code to make playlists only play once by default, but have also edited the commands to allow for playlist repeating.  I'd be willing to share the code with you if you want.  Just let me know.

**Comment by Twentysix26** [comment]
I'm not going to look into it closely but the current !prev always worked for me, except when the previous song was an invalid link. Anyway, thanks for the offer but I'm currently rewriting Red. It's pretty much a matter of days before I release it.

**Comment by Atlowell** [comment]
The bug only appears when you !prev on the first song of a playlist, at which point it will play the first song over again instead of wrapping around to the back.  You may have intended this but the next command wraps around to the front so i figured it should work like a circular dll.

Anyways, how big is the rewrite?  Are you changing the entire structure?

**Comment by Twentysix26** [comment]
Yes, it will be completely modular. It's based on discord.py's command extension. The original was getting way too hard to work on (poorly structured to begin with), and since I had to rewrite audio entirely anyway I decided it was the right time to rewrite the whole thing

**Comment by Atlowell** [comment]
Sounds awesome.  I'm looking forward to tinkering with it.
