### ISSUE TITLE
Feature Request: an option to make the audio commands admin only

### ISSUE THREAD

**Issue by scummboy** [Twentysix26/Red-DiscordBot#41]
Would it be possible to have a setting to limit the audio commands to the Admin group? On larger servers this could be very helpful and limit abuse.

**Comment by xnaas** [comment]
To add, I think it would be nice if setting what commands were admin only was a simple task. For instance, maybe I want to allow anyone to `addcom` but I don't want anyone to be able to `delcom` or `editcom`. :)

**Comment by Asute** [comment]
@xnaas In V1, there's a setting that allows only Admins to edit custom commands (```EDIT_CC_ADMIN: True```). Removing them could only be done by the creator or Admins as well. Not too sure about V2.

**Comment by TheNarwhal** [comment]
I'm fine with everyone being able to add songs, but I'd love control over who can skip them. With my server, it's a bit of a problem if everyone can skip songs they don't like, as no songs would ever finish.

**Comment by tekulvw** [comment]
Encompassed by #187 it'll be a while but it'll get there. Keep an eye on the `core-changes` branch
