### ISSUE TITLE
[v2] Whitelist Security Issue

### ISSUE THREAD

**Issue by NotGray** [Twentysix26/Red-DiscordBot#48]
If you whitelist by name, people can spoof the names of other people who do have permissions.

**Comment by Asute** [comment]
Have you tried whitelisting using the person's ID instead of their name? Usually name is not recommended for that reason.

**Comment by NotGray** [comment]
Yup. It wouldn't add properly.

**Comment by Twentysix26** [comment]
I don't know where you got the impression that the whitelist works by name. It doesn't.

**Comment by NotGray** [comment]
This is for the v2 bot

When you type: !help whitelist

When using: !whitelist add <userid>
It doesn't register it. But it does register: !whitelist add @<username> or
!whitelist add <username>

**Comment by Twentysix26** [comment]
What would be the advantage of directly adding user ids? Chances are that the user you want to add is already in your server, might as well add directly its name.

I'm not sure you get it, so I'm explaining this again. Whitelist is based on IDs. When you add an user, its ID get added in the list. Copying the user's name after that is useless, as the ID would still be different

**Comment by NotGray** [comment]
What if there are multiple users with the same name at the time of
whitelist?
Which user ID would it decide to whitelist then?

Sorry if I'm coming off as an ass, I'm not trying to be as I'm a fan of
your work but just am trying to understand this bit is all

**Comment by Asute** [comment]
You @ mention the person you want to whitelist and the bot will choose that person mentioned.

**Comment by NotGray** [comment]
What if there are multiple users with the same username on your server at the time?
Which one does the bot decide to add?

**Comment by Asute** [comment]
Like I said, you can specifically choose who to @ mention.

**Comment by NotGray** [comment]
My apologies, was a client-side error on my end.
Apparently the @ wasn't showing any results at the time.
A client restart fixed this error.

Sorry for the confusion and waste of time :(
