### ISSUE TITLE
Feature Request: Now Playing + Deleting

### ISSUE THREAD

**Issue by GreenLED99** [Twentysix26/Red-DiscordBot#52]
1) Once a song has been placed into the queue or is now playing then delete the link posted and say "Now playing...." 

2) another user encountered errors using !play http://www.youtube.com/watch?v=YQHsXMglC9A
but when they put in a new link it worked... IDK whats wrong with it and ive been staring at it for a little xD

**Comment by tekulvw** [comment]
Encompassed by #185
