### ISSUE TITLE
Suggestion: Utilise "In-Game" as a "Now Playing" thing

### ISSUE THREAD

**Issue by HDG-MrDeeJay** [Twentysix26/Red-DiscordBot#54]
As it says on the tin. I'm trying to do this myself, but with literally no experience with Python... I'm setting off syntax errors or trying to call on shit that doesn't exist there.

Take a look and laugh at my attempt to add it...

```PYTHON	
def getVideo(self, url):
		try:
			yt = youtube_dl.YoutubeDL(youtube_dl_options)
			v = yt.extract_info(url, download=False)
			if not os.path.isfile("cache/" + v["id"]):
				logger.info("Track not in cache, downloading...")
				v = yt.extract_info(url, download=True)
			self.currentTitle = v["title"]
			client.change_status(discord.Game(name=v["title"]))		
			return v["id"]
		except Exception as e:
			logger.error(e)
			return False
```

**Comment by Twentysix26** [comment]
Red is being rewritten, the old version is no longer being worked on. This feature already exists in [the rewrite](https://github.com/Twentysix26/Red-DiscordBot/tree/develop).
