### ISSUE TITLE
Prevent queue looping

### ISSUE THREAD

**Issue by studDUGY** [Twentysix26/Red-DiscordBot#57]
Hey Twentysix! Thanks a lot adding SoundCloud support on the developer branch (don't know where else to say it, lol). Will definitely donate whenever I'm not a poor student anymore, haha.

I was just wondering, is there any way to prevent the queue from looping? For example, if I play just a single song with "!play", it will loop continously until someone types "!stop".

I looked everywhere and even tried disabling queue mode but it's still looping everytime.

Thanks!

**Comment by Twentysix26** [comment]
Queue doesn't loop, playlists do.
At the moment !play puts the song in a single song playlist so it does loop. I'm planning to change it though

**Comment by Twentysix26** [comment]
Fixed
