### ISSUE TITLE
Unknown issue preventing Red startup (V2)

### ISSUE THREAD

**Issue by HDG-MrDeeJay** [Twentysix26/Red-DiscordBot#58]
![http://i.imgur.com/fqZS4jH.png](http://i.imgur.com/fqZS4jH.png)

Prior to this error occuring, my system administrator decided to do a shitton of fucking around followed by a system restore. After reinstalling python package dependencies (such as youtube_dl etc) and repairing the python installation (in an attempt to isolate the issue), I failed to identify the problem, or resolve it. It occurs after it prints "Loading Cogs" shortly after displaying that message, it starts a traceback, most of which is visible in that screenshot. I also tried rebooting while writing this message, but as I feared, that did nothing.

**Comment by HDG-MrDeeJay** [comment]
Should note: V1 (which was functional prior) is providing a similar error, specifically "Task was destroyed but it is pending!"

**Comment by Twentysix26** [comment]
Ignore "task was destroyed", that's unrelated. The problem is SSL certificates. I got the same thing on Windows Server and I wasn't able to solve it after a lot of fiddling. Ended up switch to ubuntu server.

**Comment by MrFlutters** [comment]
I fixed the following error by simply reinstalling SSL.,

**Comment by HDG-MrDeeJay** [comment]
Haha, well TY @MrFlutters for fixing it for me xD.

Kinda want to learn Python now, but :(

**Comment by Twentysix26** [comment]
Glad to hear you solved the issue

**Comment by Twentysix26** [comment]
For future reference, another user with the same issue solved it by simply visiting Discord's website once
