### ISSUE TITLE
Queue command to show queue

### ISSUE THREAD

**Issue by xnaas** [Twentysix26/Red-DiscordBot#63]
Would be nice if typing `!queue` (with no link) or something similar would show what's coming up in the current queue. :)

**Comment by xnaas** [comment]
I'm on the development branch. Sorry if this is already in v1.

**Comment by jaw3l** [comment]
+1

**Comment by Asute** [comment]
~~Update v2.~~ Nothing to see here

**Comment by Asute** [comment]
D:< Apparently I misread/misunderstood. Reopening. //kicks @Twentysix26

**Comment by Twentysix26** [comment]
Aaand done.

//shakes @Asute
