### ISSUE TITLE
Multiple Choice Quizzes (With Sass)?

### ISSUE THREAD

**Issue by JapanYoshi** [Twentysix26/Red-DiscordBot#774]
My friend and I want to make a You Don't Know Jack-like bot, but we both lack the appropriate knowledge to program one. Would it be possible to have multiple choice questions returning a reaction after picking an option?

The question data, I think, would look something like this:
```
QMC`40000`random`If you were the guy who had to write obituaries for every dead Shakespeare character, which of the following would you fortunately not have to write?`1`fell from a cliff`People get stabbed but at least they didn't fall from heights. That'd just hurt.`0`bitten by a snake`Yeowch, your bad answer is almost as painful as a snake bite.`0`baked into a pie`Well, it must have been a spectacle my tongue would rather pass up on.`0`mauled by a bear`After that answer, you should go ahead and exit, pursued by bear.`EQ`
```
QMC starts a multiple choice question, followed by the point value and whether to rardomize the order of options. The question text follows, and then options in this format: 1 for correct and 0 for incorrect, the text of the option, and the remark upon choosing that answer (could be a blank string). EQ ends the question.

The parsing should ignore newlines, so the questions can be human-readable:
```
QMC`40000`random`
If you were the guy who had to write obituaries for every dead Shakespeare character, which of the following would you fortunately not have to write?`
1`fell from a cliff`People get stabbed but at least they didn't fall from heights. That'd just hurt.`
0`bitten by a snake`Yeowch, your bad answer is almost as painful as a snake bite.`
0`baked into a pie`Well, it must have been a spectacle my tongue would rather pass up on.`
0`mauled by a bear`After that answer, you should go ahead and exit, pursued by bear.`
EQ`
```

This source code may yield something like this from the bot:

>**Question 1 (for 40000 points)**
>❓If you were the guy who had to write obituaries for every dead Shakespeare character, which of the following would you fortunately not have to write?
>1⃣ bitten by a snake
>2⃣ fell from a cliff
>3⃣ mauled by a bear
>4⃣ baked into a pie

and responses would take one digit as an input. (Use letters if it overflows)

(assume the user answers 1)

>1⃣ Yeowch, your bad answer is almost as painful as a snake bite. ❌

**Comment by tekulvw** [comment]
Might be useful as a third party cog. As of now there's little to no chance this makes it into V2 and there has been no chatter about including it in V3.

**Comment by Twentysix26** [comment]
This might be better suited as a 3rd party cog

**Comment by JapanYoshi** [comment]
Thanks for your reply. How would I go about coding this as "a 3rd party cog"?
